/* Constants for use in the personality recommendation reducer */
export const GET_CAREER_RECOMMENDATIONS_REQUEST =
  'GET_CAREER_RECOMMENDATIONS_REQUEST';
export const GET_CAREER_RECOMMENDATIONS_SUCCESS =
  'GET_CAREER_RECOMMENDATIONS_SUCCESS';
export const GET_CAREER_RECOMMENDATIONS_FAIL =
  'GET_CAREER_RECOMMENDATIONS_FAIL';
export const GET_CAREER_RECOMMENDATIONS_RESET =
  'GET_CAREER_RECOMMENDATIONS_RESET';
export const ORDER_CAREERS_ASCENDING = 'ORDER_CAREERS_ASCENDING';
export const ORDER_CAREERS_DESCENDING = 'ORDER_CAREERS_DESCENDING';
