/* Constants for use in the  personality reducer*/
export const GET_PERSONALITY_INFO_REQUEST = 'GET_PERSONALITY_INFO_REQUEST';
export const GET_PERSONALITY_INFO_SUCCESS = 'GET_PERSONALITY_INFO_SUCCESS';
export const GET_PERSONALITY_INFO_FAIL = 'GET_PERSONALITY_INFO_FAIL';
export const GET_PERSONALITY_INFO_RESET = 'GET_PERSONALITY_INFO_RESET';
