# Generated by Django 3.2.4 on 2021-07-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_customuser_quizdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='quizData',
            new_name='quizDate',
        ),
    ]
